Default Users
Manager: Basic manager_1:01_manager_01
Analyst1: Basic analyst_1:01_analyst_01
Analyst2: Basic analyst_2:02_analyst_02
User1: Basic good_user_1:01_user_01
User2: Basic good_user_2:02_user_02


### Retrieve all content as employee
GET http://34.239.105.123:8080/contents
Authorization: Basic manager_1:01_manager_01

### Retrieve all content as customer (normal user)
GET http://localhost:8080/contents
Authorization: Basic good_user_1:01_user_01

### Retrieve a specific content (only emp)
GET http://localhost:8080/contents/1
Authorization: Basic manager_1:01_manager_01

### Create a new content
POST http://localhost:8080/contents
Authorization: Basic good_user_1:01_user_01
Content-Type: application/json

{
    "title": "Created Content 1",
    "summary": "Created Summary 1",
    "link": "http://createdlink1.com",
    "content": "Created Content 1"
}

### Update a created content - Employee
PUT http://localhost:8080/contents/1
Authorization: Basic analyst_1:01_analyst_01
Content-Type: application/json

{
    "title": "New Title 1",
    "summary": "New Summary 1",
    "link": "http://newlink1.com",
    "content": "New Content 1",
    "approved": true
}

### Update a created content - Manager
PUT http://localhost:8080/contents/1
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "title": "New Title 2",
    "summary": "New Summary 2",
    "link": "http://newlink2.com",
    "content": "New Content 2",
    "approved": true
}

### Get top headlines
GET http://localhost:8080/content/test/topheadlines

### Get specific query
GET http://localhost:8080/content/test/specificQuery/CDL