###
#GET http://localhost:8080/employees

###
GET http://localhost:8080/customers


###
GET http://localhost:8080/pricetest?stock=S68.SI

###
POST http://localhost:8080/generatefake

###
GET http://localhost:8080/users

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "good_user_1",
    "password": "01_user_01"
}


###

GET http://localhost:8080/users
Authorization: Basic manager_1:01_manager_01

###
GET http://localhost:8080/customers/4
Authorization: Basic manager_1:01_manager_01
###
GET http://localhost:8080/customers/1

###
POST http://localhost:8080/empolyee/customerstatus/1/deactivate

###
POST http://localhost:8080/employee/customerstatus
Content-Type: application/json

{
    "customer_id":1,
    "active": false
}

###
PUT http://localhost:8080/content/approveContent/1


###
GET http://localhost:8080/accounts

###
GET http://localhost:8080/transfers

###
POST http://localhost:8080/transfer/makeTransfer
Content-Type: application/json

{
    "from_acc": 1,
    "to_acc": 2,
    "amount": 2000
}


### test section

##Manager

### -- View Users 

GET http://localhost:8080/users
Authorization: Basic manager_1:01_manager_01

### -- View Accounts

GET http://localhost:8080/accounts
Authorization: Basic manager_1:01_manager_01

### -- View Customers

GET http://localhost:8080/customers
Authorization: Basic manager_1:01_manager_01


### -- View Individual Customers

GET http://localhost:8080/customers/3
Authorization: Basic manager_1:01_manager_01


### -- View Portfolios

GET http://localhost:8080/portfolios
Authorization: Basic manager_1:01_manager_01

### -- View Individual Portfolio by user (use this)

GET http://localhost:8080/portfolio
Authorization: Basic good_user_2:02_user_02

### Customer

### -- Create Account From Customer1
POST http://localhost:8080/accounts
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_1",
    "balance": 100000.0,
    "available_balance": 100000.0
}

### -- Create Account From Customer2
POST http://localhost:8080/accounts
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_2",
    "balance": 1000.0,
    "available_balance": 1000.0
}

###
### -- Create Invalid Account (invalid username)
POST http://localhost:8080/accounts
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "s_2",
    "balance": 1000.0,
    "available_balance": 1000.0
}

################ CREATE USER and CUSTOMER
### -- Create User3
POST http://localhost:8080/user/createUser
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_3",
    "password": "testpassword",
    "authorities": "ROLE_USER"
}

### -- Create CUSTOMER
POST http://localhost:8080/user/createUser/customer
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_3",
    "full_name": "Good User",
    "nric" : "S2345678u",
    "phone" : "99999999",
    "address": "123 Still Rd"
}


### Bad Case Check
### -- Create User4
POST http://localhost:8080/user/createUser
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_4",
    "password": "testpassword",
    "authorities": "ROLE_USER"
}

###
### -- Create CUSTOMER (FAIL, invalid username)
POST http://localhost:8080/user/createUser/customer
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user4",
    "full_name": "Good User",
    "nric" : "1234567",
    "phone" : "999",
    "address": "123 Still Rd"
}

### -- Create CUSTOMER (FAIL, invalid nric)
POST http://localhost:8080/user/createUser/customer
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_4",
    "full_name": "Good User",
    "nric" : "1234567",
    "phone" : "999",
    "address": "123 Still Rd"
}


### -- Create CUSTOMER (FAIL, invalid phone number)
POST http://localhost:8080/user/createUser/customer
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_4",
    "full_name": "Good User",
    "nric" : "S1234567I",
    "phone" : "12345678",
    "address": "123 Still Rd"
}

###
PUT http://localhost:8080/customers/1
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "id":1,
    "username": "good_user_4",
    "password":"abcde1234",
    "full_name": "Good User",
    "nric" : "S1234567I",
    "phone" : "12345678",
    "address": "123 Still Rd"
}

### -- Create CUSTOMER (PASS, minimalist input)
POST http://localhost:8080/user/createUser/customer
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_4",
    "full_name": "Good User"

}

### -- Initialise Stock Repository (SGX Top 30 - Quantity: 20,000)
POST http://localhost:8080/stock/initialiseStock


### -- View Stock Repository
GET http://localhost:8080/stocks

### -- View Trade Repository
GET http://localhost:8080/trades

###
GET http://localhost:8080/pricetest?stock=A17U.SI

### - Create Account 1 for Customer 1 if not done above
POST http://localhost:8080/accounts
Authorization: Basic good_user_1:01_user_01
Content-Type: application/json

{
    "username": "good_user_1",
    "balance": 100000.0,
    "available_balance": 100000.0
}

### - Create buy trade for Customer 3 - Account 1
POST http://localhost:8080/trades
Authorization: Basic good_user_2:01_user_02
Content-Type: application/json

{
    "action":"buy", 
    "symbol":"A17U.SI",
    "quantity":500,  
    "bid":0, 
    "account_id":1, 
    "customer_id":3, 
    "status":"open"
}

### -- View asset 
GET http://localhost:8080/assets

### - Create sell trade for Customer 1 - Account 1
POST http://localhost:8080/trades
Authorization: Basic good_user_2:01_user_02
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U.SI",
    "quantity":500,  
    "ask":0, 
    "account_id":2, 
    "customer_id":1, 
    "status":"open"
}
### -- cancel the trade for customer 1 - 
PUT http://localhost:8080/trades/1
Authorization: Basic good_user_2:01_user_02

### -- view specific trade based on trade id -
GET http://localhost:8080/trades/1
Authorization: Basic good_user_2:01_user_02




### - View all contents
GET http://localhost:8080/contents
Authorization: Basic manager_1:01_manager_01


### - Approve a content
PUT http://localhost:8080/content/approveContent/1
Authorization: Basic manager_1:01_manager_01

### - View approved contents
GET http://localhost:8080/content/approvedContents
Authorization: Basic manager_1:01_manager_01


