###
#GET http://localhost:8080/employees

###
#GET http://localhost:8080/customers


###
POST http://localhost:8080/perform_logout

###
POST http://localhost:8080/login_page
Authorization: Basic Admin_1 Admin_password
Content-Type: application/json

{
    "username": "Admin_1"
}


###
GET http://localhost:8080/users
Authorization: Basic Admin_1:Admin_password

###
GET http://localhost:8080/contents

###
GET http://localhost:8080/customers/1

###
POST http://localhost:8080/empolyee/customerstatus/1/deactivate

###
POST http://localhost:8080/employee/customerstatus
Content-Type: application/json

{
    "customer_id":1,
    "active": false
}

###
PUT http://localhost:8080/content/approveContent/1


###
GET http://localhost:8080/accounts

###
POST http://localhost:8080/account/createAccount
Content-Type: application/json

{
    "customer_id": 1,
    "balance": 10000,
    "available_balance": 5000
}

###
POST http://localhost:8080/account/createAccount
Content-Type: application/json

{
    "customer_id": 2,
    "balance": 2000,
    "available_balance": 1000
}


###
GET http://localhost:8080/transfers

###
POST http://localhost:8080/transfer/makeTransfer
Content-Type: application/json

{
    "from_acc": 1,
    "to_acc": 2,
    "amount": 2000
}

###
GET http://localhost:8080/trades

###
POST http://localhost:8080/trades
Content-Type: application/json

{
    "action": "buy",
    "symbol":"A17U",
    "quantity":1000, 
    "bid":3.28, 
    "ask":3.27, 
    "avg_price":3.30,
    "filled_quantity":0,
    "date": "2020-09-17 06:43:19.77",
    "account_id":1234, 
    "customer_id":1234,
    "status":"open"
}

###
GET http://localhost:8080/trades/1

###
DELETE http://localhost:8080/trades/1

