
### -- View account Repository
GET https://localhost:8443/api/accounts
Authorization: Basic manager_1:01_manager_01

### -- View customers info
GET https://localhost:8443/api/customers



### -- View all available Stock Info (only Role user)
GET https://localhost:8443/api/stocks
Authorization: Basic ryverBank:ryverBankPassword

### -- View specific Stock Info (only Role user)
GET https://localhost:8443/api/stocks/A17U
Authorization: Basic ryverBank:ryverBankPassword


### -- View specific Stock Info (with invalid symbol  -> 400)
GET https://localhost:8443/api/stocks/A17U.SI
Authorization: Basic ryverBank:ryverBankPassword



### -- View Individual Portfolio (only Role user)
GET https://localhost:8443/api/portfolio
Authorization: Basic ryverBank:ryverBankPassword

### -- View Individual Portfolio
GET https://localhost:8443/api/portfolio
Authorization: Basic good_user_1:01_user_01

### -- View Individual Portfolio
GET https://localhost:8443/api/portfolio
Authorization: Basic good_user_2:02_user_02

### -- View Individual Portfolio    (if Manager view -> forbidden)
GET https://localhost:8443/api/portfolio
Authorization: Basic manager_1:01_manager_01



### -- View Trade Repository (Manager can view all list) (Extra)
GET https://localhost:8443/api/trades
Authorization: Basic manager_1:01_manager_01

### -- View all trades belongs to user
GET https://localhost:8443/api/trades
Authorization: Basic ryverBank:ryverBankPassword

### -- View all trades belongs to user
GET https://localhost:8443/api/trades
Authorization: Basic good_user_1:01_user_01

### -- View all trades belongs to user
GET https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02


### - Create trade (with invalid/no account id -> 400)
### check if customer doesnt own the account and tries to trade
POST https://localhost:8443/api/trades
Authorization: Basic ryverBank:ryverBankPassword
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U",
    "quantity":500,  
    "ask":5, 
    "account_id": 2,
    "customer_id":1, 
    "status":"open"
}

### - Create trade (with invalid customer id -> 400)
POST https://localhost:8443/api/trades
Authorization: Basic ryverBank:ryverBankPassword
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U",
    "quantity":500,  
    "ask":5,  
    "account_id":1,
    "customer_id":2,
    "status":"open"
}

### - Create trade (with invalid symbol -> 400)
POST https://localhost:8443/api/trades
Authorization: Basic ryverBank:ryverBankPassword
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17",
    "quantity":500,  
    "ask":5, 
    "account_id":1,
    "customer_id":1, 
    "status":"open"
}

### - Create trade (with invalid quantity -> 400)
POST https://localhost:8443/api/trades
Authorization: Basic ryverBank:ryverBankPassword
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U",
    "quantity":550,  
    "ask":5,  
    "account_id":1,
    "customer_id":1,
    "status":"open"
}



### - Testing buy > available balance  --> throw insufficient fund
### -- View account
GET https://localhost:8443/api/accounts/3
Authorization: Basic good_user_2:02_user_02

### - Create buy trade
POST https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02
Content-Type: application/json

{
    "action":"buy", 
    "symbol":"C31",
    "quantity":500,  
    "bid":1000, 
    "account_id":3, 
    "customer_id":3
}

### -- View account (no changes in account balance)
GET https://localhost:8443/api/accounts/3
Authorization: Basic good_user_2:02_user_02



### - Testing buy as much as possible 
### -- View trade
GET https://localhost:8443/api/trades
Authorization: Basic good_user_1:01_user_01

### - Create buy trade
POST https://localhost:8443/api/trades
Authorization: Basic good_user_1:01_user_01
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U",
    "quantity":500,  
    "ask":30, 
    "account_id":2, 
    "customer_id":2
}

### - Checking have enough stock for multiple selling 
POST https://localhost:8443/api/trades
Authorization: Basic good_user_1:01_user_01
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U",
    "quantity":18000,  
    "ask":30, 
    "account_id":2, 
    "customer_id":2
}

### -- View account
GET https://localhost:8443/api/accounts
Authorization: Basic manager_1:01_manager_01

### -- View trade
GET https://localhost:8443/api/trades
Authorization: Basic good_user_1:01_user_01

### -- View trade
GET https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02

### - Create buy trade
POST https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02
Content-Type: application/json

{
    "action":"buy", 
    "symbol":"A17U",
    "quantity":3000,  
    "bid":30, 
    "account_id":3, 
    "customer_id":3
}

### -- View Portfolio
GET https://localhost:8443/api/portfolios
Authorization: Basic manager_1:01_manager_01


### -- View account
GET https://localhost:8443/api/accounts/3
Authorization: Basic good_user_2:02_user_02


### -- Test
### -- cancel the open trade 
PUT https://localhost:8443/api/trades/1
Authorization: Basic ryverBank:ryverBankPassword


### -- view specific trade by id which belong to user
GET https://localhost:8443/api/trades/2
Authorization: Basic ryverBank:ryverBankPassword

### -- cancel the filled trade
PUT https://localhost:8443/api/trades/2
Authorization: Basic ryverBank:ryverBankPassword


### -- cancel the filed or partial-filled trade
PUT https://localhost:8443/api/trades/60
Authorization: Basic good_user_1:01_user_01



### - Test sell stock which is not in assets -> 404 ?? 400
### - Create sell trade that can be fufilled 
POST https://localhost:8443/api/trades
Authorization: Basic ryverBank:ryverBankPassword
Content-Type: application/json

{
    "action":"sell", 
    "symbol":"A17U",
    "quantity":500,  
    "ask":0, 
    "account_id":1, 
    "customer_id":1, 
    "status":"open"
}



### - Testing -- customers buy on 2 different accounts -> both reflected on portfolio
### create a new account for user 2     //try to fix
POST http://localhost:8080/accounts
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "username": "good_user_2",
    "balance": 10000.0,
    "available_balance": 10000.0
}

### buy using first account 
POST https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02
Content-Type: application/json

{
    "action":"buy", 
    "symbol":"A17U",
    "quantity":100,  
    "ask":0, 
    "account_id":3, 
    "customer_id":3, 
    "status":"open"
}

### buy using second account 
POST https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02
Content-Type: application/json

{
    "action":"buy", 
    "symbol":"A17U",
    "quantity":500,  
    "ask":0, 
    "account_id":4, 
    "customer_id":4, 
    "status":"open"
}

### -- View Individual Portfolio
GET https://localhost:8443/api/portfolio
Authorization: Basic good_user_2:02_user_02

### - Testing
### create after hour trade
POST https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02
Content-Type: application/json

{
    "action":"buy", 
    "symbol":"A17U",
    "quantity":500,  
    "ask":0, 
    "date":"2020-11-02T11:44:44.797",
    "account_id":3, 
    "customer_id":3, 
    "status":"open"
}

### view trade of user
GET https://localhost:8443/api/trades
Authorization: Basic good_user_2:02_user_02

### view all trade
GET https://localhost:8443/api/trades
Authorization: Basic manager_1:01_manager_01