Default Users
Manager: Basic manager_1:01_manager_01
Analyst1: Basic analyst_1:01_analyst_01
Analyst2: Basic analyst_2:02_analyst_02
User1: Basic good_user_1:01_user_01
User2: Basic good_user_2:02_user_02

###
GET https://localhost:8443/api/trades
Authorization: Basic manager_1:01_manager_01

###
GET https://ryverbank.digital/api/users

###
POST https://ryverbank.digital/reset

###
GET https://ryverbank.digital/api/trades
Authorization: Basic manager_1:01_manager_01

###
POST http://localhost:8080/accounts/3/transactions
Authorization: Basic good_user_2:02_user_02
Content-Type: application/json

{
    "from": 3,
    "to": 2,
    "amount": 10000.0
}


###
POST http://localhost:8080/customers
Authorization: Basic manager_1:01_manager_01
Content-Type: application/json

{
    "full_name": "John Tan",
    "nric": "S8529649C",
    "phone": "93233235",
    "address": "27 Jalan Alamak S680234",
    "username": "good_user_1",
    "passowrd": "01_user_01",
    "authorities": "ROLE_USER",
    "active": true
}